### ISSUE TITLE
Inquiry on Inference speed

### ISSUE THREAD

**Issue by yj7082126** [jeanne-wang/svd_keyframe_interpolation#10]
Thank you for the wonderful research!

After I downloaded the checkpoints I was able to reproduce the results shown in the original paper. The overall inference took about 10 minutes and 17 seconds on a single A100 80GB GPU. Is this the intended speed, or is there any method to make it faster, or am I missing something?

Thanks,
Patrick

**Comment by jeanne-wang** [comment]
Hi Patrick, thanks for the interest in the work. Yes, if you run with the default parameters, it can take up to 10 minutes with A100. There are a few things you can adjust to reduce the inference time: 1. use num_inference_steps=25 instead of 50, this should cause minimum effect to the results. 2. reduce noise_injection_steps, use less number of injection steps might lead to slight blending artifacts.  You can try at your convenience.

**Comment by Huster-Hq** [comment]
> Thank you for the wonderful research!
> 
> After I downloaded the checkpoints I was able to reproduce the results shown in the original paper. The overall inference took about 10 minutes and 17 seconds on a single A100 80GB GPU. Is this the intended speed, or is there any method to make it faster, or am I missing something?
> 
> Thanks, Patrick

Hello, it seems that the file (diffusion_pytorch_model.safetensors) I downloaded could not be successfully loaded, could you please share the file you downloaded with me? My errors are as follows:

`  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 108, in load_state_dict
    return safetensors.torch.load_file(checkpoint_file, device="cpu")
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/safetensors/torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 114, in load_state_dict
    if f.read().startswith("version"):
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte`
