### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by zijieloooooou** [jeanne-wang/svd_keyframe_interpolation#4]
May I ask how much GPU memory is approximately required for model inference? I am using an A100 (40GB) and encountering a 'cuda out of memory' error.

**Comment by johndpope** [comment]
i shrunk down to 512 same problem.
giving this a go now -
```shell
for file in *.png; do         
    convert "$file" -resize 256x "$file"
done
```

**Comment by zhou-linpeng** [comment]
you can modified
`
frames = pipe(image1=frame1, image2=frame2, 
                num_inference_steps=args.num_inference_steps, 
                generator=generator,
                weighted_average=args.weighted_average,
                noise_injection_steps=args.noise_injection_steps,
                noise_injection_ratio= args.noise_injection_ratio,
    ).frames[0]
`
to 
`
frames = pipe(image1=frame1, image2=frame2, 
                num_inference_steps=args.num_inference_steps, 
                generator=generator,
                weighted_average=args.weighted_average,
                noise_injection_steps=args.noise_injection_steps,
                noise_injection_ratio= args.noise_injection_ratio,
                decode_chunk_size=2
    ).frames[0]
`
in keyframe_interpolation.py

**Comment by jeanne-wang** [comment]
Yes, if you use smaller decode_chunk_size, it can fit into A40. We use decode_chunk_size=25 to achieve best results
